const streetNames = [
    "Bayerwaldstraße",
    "Bahnhofstraße",
    "Am Sportplatz",
    "Dorfstraße",
    "Kirchhammer Straße",
    "Georg-Ettlinger-Straße",
    "Neutorgraben",
    "Fasanenallee",
    "Pfarrer-Stirner-Straße",
    "Hauptstraße",
    "Passauer Straße",
    "Adalbert-Stifter-Straße",
    "Maierhofstraße",
    "Ostuzzistraße",
    "Auerspergstraße",
    "Grünaustraße",
    "Bahnsteg",
    "Pionierstraße",
    "Schärdinger Straße",
    "Am Burgberg",
    "Eglseerstraße",
    "Dr.-Emil-Brichta-Straße",
    "Messestraße",
    "Wörthstraße",
    "Schießstattweg",
    "Steinbachstraße",
    "Greppenweg",
    "Danziger Straße",
    "Innstraße",
    "Augustinergasse",
    "Lupingäßchen",
    "Sagmeisterweg",
    "Bierweg",
    "Hammerbachstraße",
    "Neustift",
    "Leopoldstraße",
    "Bischof-Heinrich-Straße",
    "Dr.-Hans-Kapfinger-Straße",
    "Döfreuth",
    "Schauerödstraße",
    "Graf-Egbert-Weg",
    "Abt-Rumpler-Straße",
    "Vornbacher Straße",
    "Neuburger Straße",
    "Graf-Tiemo-Straße",
    "Leonhard-Paminger-Straße",
    "Krummauer Straße",
    "Spitalhofstraße",
    "Äußere Spitalhofstraße",
    "Obernzeller Straße",
    "Fuchsbauerweg",
    "Kapuzinerstraße",
    "Stelzhamerstraße",
    "Hochstraße",
    "Spitzbergstraße",
    "Bischof-Altmann-Straße",
    "Haitzinger Straße",
    "Sailerwöhr",
    "Haitzinger Brücke",
    "Giselastraße",
    "Sechzehnerstraße",
    "Marienbrücke",
    "Karolinenplatz",
    "Nikolastraße",
    "Ludwigsplatz",
    "Am Schanzl",
    "Rueland-Frueauf-Straße",
    "Haissengasse",
    "Badhausgasse",
    "Obere Bahnhofstraße",
    "Untere Bahnhofstraße",
    "Obere Donaulände",
    "Haarschedl",
    "Brandweg",
    "Schreinerholzweg",
    "Gutenbergstraße",
    "Achatiusstraße",
    "Innpromenade",
    "Franz-Josef-Strauß-Brücke",
    "Mariahilfberg",
    "Obere Vorstadt",
    "Rosenbergerweg",
    "Netzerstraße",
    "Gartenstraße",
    "Bahnweg",
    "Kraftstraße",
    "Regensburger Straße",
    "Ort",
    "Bräugasse",
    "Innbrückgasse",
    "Fritz-Schäffer-Promenade",
    "Prinzregent-Luitpold-Brücke",
    "Römerplatz",
    "Rathausplatz",
    "Höllgasse",
    "Mariahilfstraße",
    "Kapuzinerplatz",
    "Mariensteg",
    "Nibelungenstraße",
    "Holzheimerstraße",
    "Frühlingstraße",
    "Bernhard-Setzer-Straße",
    "Dr.-Geiger-Weg",
    "Gabelsbergerstraße",
    "Ilzbrücke",
    "Angerstraße",
    "Fürstenzeller Straße",
    "Paulusbogen",
    "Rindermarkt",
    "Residenzplatz",
    "Donaukai",
    "Ludwigstraße",
    "Anton-Niederleuthner-Brücke",
    "Dr.-Ernst-Derra-Straße",
    "Sinzendorfstraße",
    "Am Tiergarten",
    "Graf-Salm-Straße",
    "Lange Straße",
    "Innsteg",
    "Voglau",
    "Fuchsengassl",
    "Jahnstraße",
    "Am Severinstor",
    "Heuwieserstraße",
    "Kohlbruck",
    "Hermann-Mayrhofer-Straße",
    "Gretli-Fuchs-Straße",
    "Erna-Schützenberger-Straße",
    "Amata-Grüner-Straße",
    "Südtiroler Straße",
    "Gütlbauerweg",
    "Dr.-Ritter-von-Scheuring-Straße",
    "Poltlbauerweg",
    "Prachatitzer Straße",
    "Poststeg",
    "Roßtränke",
    "Weinleitenweg",
    "Holzmannstraße",
    "Franz-Wimmer-Straße",
    "Johann-Riederer-Straße",
    "Graneckerstraße",
    "Vornholzstraße",
    "Karlsbader Straße",
    "Gleiwitzer Straße",
    "Breslauer Straße",
    "Am Döbldobl",
    "Söldenpeterweg",
    "Reichenberger Straße",
    "Königsberger Straße",
    "Görlitzer Straße",
    "Liegnitzer Straße",
    "Vogelweiderstraße",
    "Innradweg",
    "Brunngasse",
    "Theresienstraße",
    "Dietrich-Bonhoeffer-Platz",
    "Heiliggeistgasse",
    "Löwengrube",
    "Alte Straße",
    "Römerstraße",
    "Neustifter Straße",
    "Kachletstraße",
    "Schleusenweg",
    "Freinberger Straße",
    "Wiener Straße",
    "Wörth",
    "Ranklhofweg",
    "Nömerberg",
    "Hofmarkstraße",
    "Hennebergerstraße",
    "Schaldinger Straße",
    "Heininger Straße",
    "Ganghoferstraße",
    "Carossastraße",
    "Richterstraße",
    "Ölberggasse",
    "Reinhard-Raffalt-Straße",
    "Martin-Seitz-Straße",
    "Hunostraße",
    "Rittsteiger Straße",
    "Am Bramerhof",
    "Wilhelm-Niedermayer-Straße",
    "Sandbergstraße",
    "Säumerweg",
    "Otto-Geyer-Straße",
    "Hauzenberger Straße",
    "Gottsdorfer Straße",
    "Bergfeldweg",
    "Leithen",
    "Christdobl",
    "Prinz-Eugen-Straße",
    "Schulbergstraße",
    "Firmiangut",
    "Sterkgäßchen",
    "Fritz-Abelein-Brücke",
    "Bräuhausgasse",
    "Halser Straße",
    "Grafenleite",
    "Hochsteinstraße",
    "Schwanthalerstraße",
    "Perlfischerweg",
    "Ferdinand-Wagner-Straße",
    "Vilshofener Straße",
    "Ries",
    "Neue Rieser Straße",
    "Neureut",
    "Patriching",
    "Tittlinger Straße",
    "Lüftlbergstraße",
    "Haselbacher Straße",
    "Hochleiten",
    "Dachsberg",
    "Adolf-Vältl-Straße",
    "Dr.-Eggersdorfer-Straße",
    "Wolf-Huber-Straße",
    "Bischof-Ulrich-Straße",
    "Rotkreuzstraße",
    "Kleiner Exerzierplatz",
    "Rudertinger Straße",
    "Grafenauer Straße",
    "Walter-Labmayer-Steig",
    "Poststraße",
    "Münchener Straße",
    "Tettenweiser Straße",
    "Abteistraße",
    "Am Seidenhof",
    "Josef-Wenzl-Straße",
    "Witikostraße",
    "Arberstraße",
    "Lusenweg",
    "Schanzlbrücke",
    "Eggendobl",
    "Parkstraße",
    "Traminer Straße",
    "Meraner Straße",
    "Kainzenweg",
    "Johann-Bergler-Straße",
    "Linzer Straße",
    "Kurallee",
    "Adolf-Langer-Weg",
    "Grenzstraße",
    "Waldesruh",
    "Unterilzmühle",
    "Stuhlberg",
    "Kehrwischinger Straße",
    "Hördterbergstraße",
    "Friedhofstraße",
    "Daxlarner Straße",
    "Am Kirchberg",
    "Stüblhäuser",
    "Rastbüchlstraße",
    "Josef-Greschniok-Straße",
    "Thermalbadstraße",
    "Pockinger Straße",
    "Füssinger Straße",
    "Maximiliantunnel",
    "Am Kurwald",
    "Klosterstraße",
    "Kirchplatz",
    "Hochrainstraße",
    "Rathausstraße",
    "Finkenstraße",
    "Johannesstraße",
    "Aidenbacher Straße",
    "Stadtplatz",
    "Simmerlingweg",
    "Weghofstraße",
    "Nepomukstraße",
    "Bachstraße",
    "Cagnes-sur-Mer-Promenade",
    "Wittgasse",
    "Große Klingergasse",
    "Kleine Klingergasse",
    "Rektor-Karl-Heinz-Pollok-Straße",
    "Franz-Stockbauer-Weg",
    "Hollergrippe",
    "Dr.-Hellge-Straße",
    "Schillerstraße",
    "Firmianstraße",
    "Von-Rudhart-Straße",
    "Westerburgerstraße",
    "Jakob-Endl-Straße",
    "Schönauerweg",
    "Erlbacher Straße",
    "Paracelsusstraße",
    "Dreisesselstraße",
    "Wolfgang-Schmid-Straße",
    "Bischof-Piligrim-Straße",
    "Kreppe",
    "Schweiklbergstraße",
    "Schießgrabengasse",
    "Hennengasse",
    "Unterer Sand",
    "Rosengasse",
    "Bischof-Wolfger-Straße",
    "Kötzstraße",
    "Dreiburgenstraße",
    "Bürgermeister-Schuh-Straße",
    "Preysingstraße",
    "Kolpingstraße",
    "Kleinfeld",
    "Ostmarkstraße",
    "Am Dentberg",
    "Ruffinstraße",
    "Wiesing",
    "Fischhauser Straße",
    "Oberer Sand",
    "Grabengasse",
    "Bankgäßchen",
    "Nagelschmiedgasse",
    "Abt-Bachmeyer-Straße",
    "Schiffmühlgasse",
    "Thomastraße",
    "Vorderhainberg",
    "Lena-Christ-Straße",
    "Zaundorf",
    "Bratfischwinkel",
    "Frauengasse",
    "Innkreis Autobahn",
    "Nibelungenplatz",
    "Am Jägersteig",
    "Oberer Schmidsberg",
    "Donaublick",
    "Schmidsberg",
    "Lukas-Kern-Straße",
    "Am Hafen",
    "Treidelweg",
    "Krankenhausstraße",
    "Kaufmannweg",
    "Tillygasse",
    "Kirchengasse",
    "Klosterweg",
    "Oppermannweg",
    "Rechenmacherweg",
    "Doktor-R.-Seiler-Straße",
    "Windschnur",
    "Uferstraße",
    "Schmiedgasse",
    "Hameter Straße",
    "Hochhäuslweg",
    "Quellenweg",
    "Bergstraße",
    "Lüfteneckerstraße",
    "Ringstraße",
    "Dr.-Türk-Straße",
    "Jägerzeile",
    "Spitalweg",
    "Am Hang",
    "Hammermühlstraße",
    "Kitzingweg",
    "Siedlungsstraße",
    "Birkenweg",
    "Max-Moser-Straße",
    "Niederndorfer Weg",
    "Hametstellen",
    "Kanzelweg",
    "Örtl",
    "Marktplatz",
    "Schloßplatz",
    "Ledererplatz",
    "Mühlenweg",
    "Hinterhainberg",
    "Zinngießergasse",
    "Zengergasse",
    "Domplatz",
    "Klaftergasse",
    "Schrottgasse",
    "Gablergasse",
    "Steinweg",
    "Schlosserstiege",
    "Berggasse",
    "Kleine Messergasse",
    "Steiningergasse",
    "Pfaffengasse",
    "Donauradweg",
    "Donaupromenade",
    "Sandbacher Straße",
    "Nelkenweg",
    "Am Büchlberg",
    "Lederergasse",
    "Schwendistraße",
    "Göttweiger Straße",
    "Schrönghamerstraße",
    "Weiding",
    "Schloßbreite",
    "Pfarrer-Hormayr-Straße",
    "Josef-Vogel-Straße",
    "Lusenstraße",
    "Rachelweg",
    "Osserweg",
    "Hösamer Feld",
    "Allinger Straße",
    "Untere Donaulände",
    "Glasergasse",
    "Donaugasse",
    "Fischerzeile",
    "Bürg",
    "Graben",
    "Alte Feuerwehrgasse",
    "Wittelsbacherring",
    "Babenbergerzeile",
    "Max-Emanuel-Straße",
    "Asamstraße",
    "Maximilianstraße",
    "Ottostraße",
    "Peter-Breu-Straße",
    "Michael-Wening-Straße",
    "Arbeostraße",
    "Altdorferstraße",
    "Anton-Brandl-Straße",
    "Carossa-Ring",
    "Bajuwarenring",
    "Armin-Knab-Straße",
    "Schlehberg",
    "Dr.-Karl-Wild-Straße",
    "Gerhardingerstraße",
    "Arnulfstraße",
    "Theolindenstraße",
    "Luitpoldinger-Ring",
    "Bertholdstraße",
    "Kothwiesstraße",
    "Agilolfingerring",
    "Garibaldstraße",
    "Alte Dorfstraße",
    "Alte Fischergasse",
    "Lautensackstraße",
    "Wolframstraße",
    "Grillparzerweg",
    "Dinglreit",
    "Oberer Galgenberg",
    "Fischerstraße",
    "Waldhofstraße",
    "Stifterweg",
    "Ortenburger Straße",
    "Eichendorffstraße",
    "Am Hammerberg",
    "Hartauerstraße",
    "Wolfachweg",
    "Roseggerstraße",
    "Kloster-Mondsee-Straße",
    "Unterer Linienweg",
    "Vilsfeldstraße",
    "Kapellenweg",
    "Sattlerweg",
    "Döblweg",
    "Rachelstraße",
    "Professor-Scharrer-Straße",
    "Meier-Helmbrecht-Straße",
    "Zeitlarner Straße",
    "Beckenzellerweg",
    "Zur Fellermühle",
    "Steinkirchen",
    "Weberstraße",
    "Hagenauerstraße",
    "Mühltalstraße",
    "Carlonegasse",
    "Ballhausstiege",
    "Welfenstraße",
    "Autharistraße",
    "Klopfingerstraße",
    "Josef-Groll-Straße",
    "Pacherstraße",
    "Jahnallee",
    "Hörnerweg",
    "Bayerisch Haibach",
    "Galgenberg",
    "Michael-Kurz-Straße",
    "Am Klosteracker",
    "Am Schullerhof",
    "An der Pfudrach",
    "Mozartstraße",
    "Waldeslustweg",
    "Am Weinberg",
    "Gellert",
    "Goethestraße",
    "Kellerweg",
    "Lessingstraße",
    "Griesbacher Straße",
    "Grafenwiesen",
    "Frauenfeld",
    "Hainberger Weg",
    "Untere Kreppe",
    "Vorderhainberger Weg",
    "Am Föhrenberg",
    "Sattlerberg",
    "Untermarkt",
    "Zellstraße",
    "Ledererfeld",
    "Hacklmühle",
    "Eichfeldstraße",
    "Am Pfarrhof",
    "Oberfeldstraße",
    "Oberfeld",
    "Wolfachauer Ring",
    "Am Stausee",
    "Unterfeldstraße",
    "Huberhöh",
    "Ritter-Tuschl-Straße",
    "Kronthalstraße",
    "Krempelweg",
    "Mühlwiese",
    "Bürgermeister-Josef-Kirschner-Straße",
    "Klosterberg",
    "Reitschusterfeld",
    "Unterthannet",
    "Zum Oberholz",
    "Zum Steinbruch",
    "Jägerfeldweg",
    "Westendstraße",
    "Viehhauser Straße",
    "Rabensteinfeld",
    "Innlände",
    "Postgasse",
    "Milberger Weg",
    "Habichtweg",
    "Bussardweg",
    "Sperberweg",
    "Alte Hördterbergstraße",
    "Gerhart-Hauptmann-Straße",
    "Keplerstraße",
    "Menzelstraße",
    "Mitterweg",
    "Warbachweg",
    "Am Kaltendörfel",
    "Gustav-Freytag-Weg",
    "Deggendorfer Straße",
    "Bergreichensteinstraße",
    "Pilsener Straße",
    "Prof.-Reiter-Straße",
    "Mühlberg",
    "Pfudrachöder Straße",
    "Ackermannstraße",
    "Schmellerstraße",
    "Fraunhoferstraße",
    "Herderstraße",
    "Kantstraße",
    "Sechssesselweg",
    "Mendelstraße",
    "Niederham",
    "Hofmark",
    "Buchbauernberg",
    "Baderstraße",
    "Schreinerstraße",
    "Rosenstraße",
    "Sportplatzweg",
    "Pfarrer-Mitterer-Straße",
    "Perusaweg",
    "Schwarzensteinerstraße",
    "Burgstraße",
    "Am Hohen Stein",
    "Sonnenweg",
    "Bienengarten",
    "Am Weiherfeld",
    "Peigertinger Straße",
    "Hochfeldstraße",
    "Schmiedweg",
    "Finkenweg",
    "Jahnweg",
    "Frühlingsstraße",
    "Im Buchet",
    "König-Schalinski-Straße",
    "Toblacher Straße",
    "Eppaner Straße",
    "Schönleitnerweg",
    "Sterzinger Straße",
    "Brixener Straße",
    "Schustergasse",
    "Am Innwerk",
    "Turmstraße",
    "Steinkatz",
    "Säumerstraße",
    "Sonnenhang",
    "Pfarrer-Winkler-Straße",
    "Jesuitengasse",
    "Michaeligasse",
    "Milchgasse",
    "Raiffeisenplatz",
    "Badstraße",
    "Pillhamer Straße",
    "Hüttinger Straße",
    "Untere Dorfstraße",
    "Eginger Straße",
    "Mühlbergstraße",
    "Am Ring",
    "Emil-Feigl-Weg",
    "Bartl-Retsch-Straße",
    "Alois-Kölbl-Weg",
    "Michael-Fischer-Straße",
    "Alois-Bürgermeister-Weg",
    "Schulstraße",
    "Hafnerberg",
    "Michael-Zettl-Weg",
    "Bärenfeldstraße",
    "Margeritenweg",
    "Lilienstraße",
    "Tulpenstraße",
    "Nelkenstraße",
    "Lindenstraße",
    "Kirchenweg",
    "Rathausweg",
    "Adalbert-Stifter-Weg",
    "Röhrenfeldstraße",
    "Blumenstraße",
    "Preintinger Straße",
    "Gaißabrücke",
    "Gaißa",
    "Lindauer Weg",
    "Holzhäuser",
    "Großhaarbach",
    "Strenberger Straße",
    "Rottalstraße",
    "Volksfeststraße",
    "Poigham",
    "Oberndorf",
    "Thalhamer Straße",
    "Gewerbering",
    "Schäfflerring",
    "Gerner Straße",
    "Hartkirchner Straße",
    "Obere Inntalstraße",
    "Inntalstraße",
    "Thaler Straße",
    "Würdinger Straße",
    "Südallee",
    "Viehhallenweg",
    "Wolfinger Straße",
    "Höhenmühler Straße",
    "Alte Innbrücke",
    "Haarer Straße",
    "Ruhstorfer Straße",
    "Sulzbachstraße",
    "Schmiedbergstraße",
    "Kirchenstraße",
    "Neuhauser Straße",
    "Pillham",
    "Buchet",
    "Haderer Straße",
    "Wittelsbacher Straße",
    "Schloßberg",
    "Lederbach",
    "Unteruttlau",
    "St.-Andreas-Straße",
    "Herzog-Odilo-Straße",
    "Steinkartstraße",
    "Am Grieskirchner Feld",
    "Karpfhamer Straße",
    "Johann-Flechseder-Straße",
    "Afham",
    "Schwaimer Straße",
    "Singham",
    "Kapellenstraße",
    "Karpfham Bahnhof",
    "Woppinger Straße",
    "Heberstraße",
    "Dorfplatz",
    "Kühnham",
    "Berger Straße",
    "Bürgermeister-Wenig-Straße",
    "Bürgermeister-Schönbauer-Straße",
    "Simbacher Straße",
    "Am Stadtplatz",
    "Indlinger Straße",
    "St. Georgen Straße",
    "Berzeliusstraße",
    "Wöhlerstraße",
    "Königswiese",
    "Rottauer Straße",
    "Rotthofer Straße",
    "Lindenweg",
    "Buchenstraße",
    "Ahornring",
    "Rotthof",
    "Oberschwärzenbacher Straße",
    "Ranzinger Straße",
    "Sonnenleite",
    "Am Osterberg",
    "Jägerweg",
    "Amselweg",
    "Marienweg",
    "Niedergrün",
    "Rapotoweg",
    "Haagstraße",
    "Maria-Schmid-Straße",
    "Seilerberg",
    "Am Steinkart",
    "Josef-Philipp-Straße",
    "Holzinger Weg",
    "Inhamer Straße",
    "Birketweg",
    "Zehentreith",
    "Neue Straße",
    "Geiselbergfeld",
    "Am Bergfeld",
    "Am Goldberg",
    "Tannenweg",
    "Sulzbacher Straße",
    "Oberreisching",
    "Aspertsham",
    "Herzog-Heinrich-Straße",
    "Von Lamberg Straße",
    "Bad Höhenstadt",
    "Wieninger Straße",
    "Grund",
    "Hans-Resch-Straße",
    "Obere Dorfstraße",
    "Jodlbauerweg",
    "Gerolinger Straße",
    "Kaiser-Leopold-Straße",
    "Jochensteiner Straße",
    "Am Jochenstein",
    "Werksiedlung",
    "Hofweg",
    "Holzhäuser Straße",
    "Lehrer-Mooser-Straße",
    "St.-Benedikt-Straße",
    "Am Rottdamm",
    "Aumühlenstraße",
    "Weberweg",
    "St.-Ulrich-Straße",
    "Weizauer Weg",
    "Bertha-von-Suttner-Straße",
    "Maria-Ward-Straße",
    "Montessoristraße",
    "Leopold-Krönner-Straße",
    "Wolfing",
    "Wollham",
    "Pram",
    "Antoniusweg",
    "Martinweg",
    "Zieglöder Straße",
    "Kurhausstraße",
    "Zieglöder Weg",
    "Waldstraße",
    "Andreas-Hofer-Straße",
    "Alte Füssinger Straße",
    "Prof.-Böhm-Straße",
    "Beethovenstraße",
    "Richard-Wagner-Straße",
    "Ludwig-Thoma-Weg",
    "Safferstettener Straße",
    "Ulmenstraße",
    "Andreasstraße",
    "Am Tennispark",
    "Sonnenstraße",
    "Pappelallee",
    "Dürnöder Weg",
    "Sonnenring",
    "Dr.-Heim-Straße",
    "Birkenallee",
    "Waldweg",
    "Erlautal",
    "Kollmering",
    "Eulenweg",
    "Josef-Hiendl-Weg",
    "Passerting",
    "Graf-Joner-Straße",
    "Franz-von-Stuck-Straße",
    "Mater-Rosa-Ring",
    "Wittelsbacherstraße",
    "Asternweg",
    "Vierjahreszeiten",
    "Am Hopfenberg",
    "Dobler Straße",
    "Franz-Gerauer-Straße",
    "Oberwesterbach",
    "Hirla",
    "Münchhamer Straße",
    "Kesselbauer Straße",
    "Oberer Markt",
    "Unterer Markt",
    "Ragern",
    "Pattenham",
    "Hans-Carossa-Straße",
    "Peter-Rosegger-Straße",
    "Asenhamer Straße",
    "Thanhamer Straße",
    "Thanham",
    "Aicha im Tal",
    "Parzham",
    "Schöffau",
    "Kolpingweg",
    "Zeller Straße",
    "Brunnenweg",
    "Kubinstraße",
    "Josef-Haydn-Straße",
    "Prof.-Dieß-Straße",
    "Anton-Bruckner-Straße",
    "Lenaustraße",
    "Moltkestraße",
    "Albert-Schweitzer-Straße",
    "Heinrich-Heine-Straße",
    "Bahnhofweg",
    "Bajuwarenstraße",
    "Stuhlbergstraße",
    "Modlerweg",
    "Herzog-Otto-Straße",
    "Alemannenstraße",
    "Herzog-Stefan-Straße",
    "Wacholderstraße",
    "Buchenallee",
    "Heidestraße",
    "Akazienweg",
    "Kastanienweg",
    "Lerchenfeldstraße",
    "Klingerfeldstraße",
    "Dresdener Straße",
    "Paula-Deppe-Straße",
    "Stiftswaldstraße",
    "Altmannstraße",
    "Wilhelm-Diess-Straße",
    "Rößlerhofweg",
    "Medienstraße",
    "Zeintlmühler Straße",
    "Mittich",
    "Mitticher Straße",
    "Untere Inntalstraße",
    "Redinger Straße",
    "Inzinger Straße",
    "Obere Römerstraße",
    "Untere Römerstraße",
    "Huberstraße",
    "Vindelikerstraße",
    "Johann-Kirschner-Straße",
    "Moospointstraße",
    "Graf-Schaunberg-Straße",
    "Eichenring",
    "Otting",
    "Jederschwing",
    "Am Rauschlberg",
    "Madauerstraße",
    "Wenzel-Jorhan-Straße",
    "Anton-Bruckner-Ring",
    "Norbert-Steger-Straße",
    "Pfarrer-Drexler-Weg",
    "Hermann-Löns-Straße",
    "Am Rottwerk",
    "Söderbergstraße",
    "Guttenbrunnstraße",
    "Watzlikweg",
    "Hans-Carossa-Weg",
    "Christinastraße",
    "Hoffmannweg",
    "Plinganserstraße",
    "Graf-Tilly-Straße",
    "Bindergasse",
    "Rennbahnweg",
    "Wilhelm-von-Rottau-Weg",
    "Gstettener Straße",
    "Steinbach",
    "Maria-am-Sand",
    "Eggersham",
    "Luragogasse",
    "Kastnergasse",
    "Wasserfeldstraße",
    "Grafenspitz",
    "St.-Georg-Straße",
    "Ratoldweg",
    "Ausbeckplatzl",
    "Dr.-Koch-Straße",
    "Geranienweg",
    "Dahlienweg",
    "Fliederweg",
    "Eichenstraße",
    "Kiefernweg",
    "Lärchenweg",
    "Buchenring",
    "Am Reiserfeld",
    "Friedensweg",
    "Heilig-Geist-Straße",
    "Wilhelm-Busch-Straße",
    "Magazinstraße",
    "Auenstraße",
    "Tränkeweg",
    "Gutenbrunnstraße",
    "Am Voglfelsen",
    "Scheffweg",
    "Schützenstraße",
    "Am Klampferberg",
    "Am Bäckergütl",
    "Am Bahnhof",
    "Rottau",
    "Lindenfeld",
    "Am Grafenholz",
    "Graf-Leopold-Ring",
    "Kreuzkoppe",
    "Mühlgang",
    "St.-Florian-Straße",
    "Bruder-Konrad-Straße",
    "Bavariastraße",
    "Lerchenweg",
    "Drosselweg",
    "Haigramstraße",
    "Eckerstraße",
    "Am Wirtsfeld",
    "Wirtsfeldring",
    "Alte Schmiede",
    "Erlengasse",
    "Pemelöd",
    "Pfarrkirchener Straße",
    "Wührerfeld",
    "Hörlstraße",
    "Ernst-Hatz-Straße",
    "Hans-Loher-Straße",
    "Dr.-Ottmar-Maurer-Straße",
    "Kleeberger Straße",
    "Kohlstatt",
    "Schimmelweg",
    "Josefshöhe",
    "Winklersteig",
    "Albrecht-Dürer-Straße",
    "Schubertstraße",
    "Haynauer Straße",
    "Pfarrerland",
    "Carlonestraße",
    "Haidzinger Straße",
    "Paumgartenweg",
    "Wexelbergerstraße",
    "Asamring",
    "Sudetenstraße",
    "Keltenweg",
    "Asperl",
    "Urfar",
    "Irchinger Straße",
    "Römerweg",
    "Leonhardistraße",
    "Herrenstraße",
    "Hart",
    "Birkhamer Straße",
    "Dr.-Atzinger-Straße",
    "Mühlweg",
    "Donau-Schwaben-Straße",
    "Langemarckstraße",
    "Doblweg",
    "Dr.-Stephan-Billinger-Straße",
    "Am Mitticher Bach",
    "Wagnerstraße",
    "St.-Vitus-Weg",
    "Lieghartinger Straße",
    "Berginger Straße",
    "Raiffeisenstraße",
    "Sportplatzstraße",
    "Rehschaln",
    "Parzgasse",
    "Hirschwirtsgaßl",
    "Klosterwinkel",
    "Freudensee",
    "Pfarrstraße",
    "Kusserstraße",
    "Im Tränental",
    "Pfarrer-Schlichting-Straße",
    "Südumgehung",
    "Am Mollnhof",
    "Dr.-von-Pichler-Platz",
    "Graf-Zeppelin-Straße",
    "Memelstraße",
    "An der Rodelwiese",
    "Budweiser Straße",
    "Mittererstraße",
    "Weinholzerweg",
    "Dieter-Stauber-Straße",
    "Otto-Zieske-Straße",
    "Winterberger Straße",
    "Josef-Großwald-Weg",
    "Racklau",
    "Teichweg",
    "Gewerbegebiet Dorfbach",
    "Anton-Pötzl-Straße",
    "Obersölden",
    "Untere Schneckenbergstraße",
    "Garhammerweg",
    "Gegenbachstraße",
    "Böhmerwaldstraße",
    "Europaplatz",
    "Höpflbergstraße",
    "Michael-Uhrmann-Straße",
    "Bergsiedlung",
    "Schmiedberg",
    "Dreihiaslstraße",
    "Otto-Zirnbauer-Straße",
    "Franz-Xaver-Kurländer-Straße",
    "Sebastian-Leicht-Straße",
    "Lilly-Zeheter-Straße",
    "Betty-Pfleger-Straße",
    "Maria-Weiß-Straße",
    "Anni-Simmeth-Weg",
    "Elise-Langesee-Weg",
    "Reinhold-Preiß-Straße",
    "Göbertsham",
    "Färberstraße",
    "Seilerstraße",
    "Galgenbergweg",
    "Würding",
    "Alte Landstraße",
    "Am Redinger Bach",
    "Stockbauersteg",
    "Reut",
    "Hofbauerngut",
    "Hofbauerngut (Triftsperre) befahren 21-6 Uhr nicht gestattet",
    "Ilztalwanderweg",
    "Triftsperre",
    "Obereichet",
    "Scheuereckerweg",
    "Pausenweg",
    "Am Höpflberg",
    "Harslemstraße",
    "Buchbinderstraße",
    "Doblingerstraße",
    "Seerundweg Rannasee",
    "Im Stockfeld",
    "Stockethof",
    "Gürtlerstraße",
    "Säcklerstraße",
    "Trimm dich Pfad",
    "Wallfahrtsstiege",
    "Auggenthal",
    "Am Schulplatz",
    "Im Hopfengarten",
    "Blisselgasse",
    "Watzmannsdorfer Ring",
    "Lambergstraße",
    "Urban-Schätzl-Straße",
    "Lorettoweg",
    "Lorettoplatz",
    "Pfarrer-Horner-Straße",
    "Christopherweg",
    "Am Badeweiher",
    "Eckerichweg",
    "Leonhardisteig",
    "Kurpromenade",
    "Lagerhausweg",
    "Bad-Füssinger-Straße",
    "Hofgartenstraße",
    "Hofer Straße",
    "Tuttiner Straße",
    "Aigner Straße",
    "Penninger Weg",
    "Schusteröd",
    "Am Alten Pfarrhof",
    "Vorderschloss",
    "Dreherbergweg",
    "Schwabgäßchen",
    "Schmidinger Feld",
    "Kirchsteig",
    "Schmidinger Höhe",
    "Kornfeldweg",
    "Schmiding",
    "Georg-Philipp-Wörlen-Straße",
    "Englmeierstraße",
    "Zieglreuth",
    "Salzweger Straße",
    "Donauwetzdorf",
    "Pangerlbergstraße",
    "Hafnerstraße",
    "Gewerbepark",
    "Hutthurmer Straße",
    "Heideweg",
    "Dettenbachstraße",
    "Kirchensteig",
    "Föhrenweg",
    "Amselsteig",
    "Lärchenstraße",
    "Am Waldpark",
    "Am Hochpegel",
    "Watzlikring",
    "Sonnensteig",
    "Ilzsteg",
    "Bschütt",
    "Untersölden",
    "Maierhofweg",
    "Pfandlweg",
    "Doktorweg",
    "Marienplatz",
    "Waldschmidtstraße",
    "Falkensteinstraße",
    "Schneidergasse",
    "Lueg",
    "Sieglberg",
    "Sieglgut",
    "Lüfteneck",
    "Löwenmühlstraße",
    "Wolfachtaler Straße",
    "Lindenallee",
    "Pfarrer-Mehrmann-Weg",
    "Moorweg",
    "Hagenau",
    "Hallhuber Straße",
    "Niederschärding",
    "Moosauweg",
    "Bäckergasse",
    "Promenade",
    "Nussbaumweg",
    "Fritz-Weidinger-Straße",
    "Passauerstraße",
    "Satzbach",
    "Witzmannsberg",
    "Schleiferberg",
    "Senefelderstraße",
    "Blasen",
    "Kesselbrunnweg",
    "Vorreiterweg",
    "Einöd",
    "Am Frauenberg",
    "Frauenbergstraße",
    "Gelbersdorf",
    "Schöllnsteiner Straße",
    "Reichsgrafenstraße",
    "Roedersteinstraße",
    "Stallerweg",
    "Waidgasse",
    "Gionstraße",
    "Winzerleite",
    "Reuthinger Weg",
    "Einbüglweg",
    "Anrichterstraße",
    "Am Urfahr",
    "Am Flugplatz",
    "Donaulände",
    "Erlengrund",
    "Maristenweg",
    "Augasse",
    "Zeindlweg",
    "Bachanger",
    "Wiesenweg",
    "Kirchenauweg",
    "Hubertusweg",
    "Schützenweg",
    "Alter Schlossweg",
    "Dürerstraße",
    "Pfarrkirchner Straße",
    "Blumenauweg",
    "Müller-Gutenbrunn-Weg",
    "Weidenweg",
    "In der Blumenau",
    "Im Aufeld",
    "Koipainterweg",
    "Paul-von-Ruestorf-Straße",
    "Rottwerkstraße",
    "Hintermarkt",
    "Graf-Tiemo-Weg",
    "Hermann-Wösner-Straße",
    "Eichenweg",
    "Paulus-Rieger-Straße",
    "Grafenstraße",
    "Professor-Dieß-Straße",
    "Ochsenstraße",
    "Haidenburger Straße",
    "Aufhauser Straße",
    "Kremsweg",
    "Gögginger Straße",
    "Hötzling",
    "Schloßwiese",
    "Haid",
    "Marstallerstraße",
    "Reisach",
    "Pleintinger Straße",
    "Heidweg",
    "Magnus-Huber-Straße",
    "Ausbach",
    "Pfaffing",
    "Schieferöd",
    "Poinzaun",
    "Oberreuthen",
    "Bischof-Landersdorfer-Straße",
    "Aumühlweg",
    "Hinteröd",
    "Am Lüftlberg",
    "Tannenstraße",
    "Peter-Maier-Straße",
    "Tannenleite",
    "August-Riesinger-Straße",
    "Dietzing",
    "Sulzholzweg",
    "Adolf-Höllinger-Straße",
    "Knorrstraße",
    "Thalau",
    "Zieglstadl",
    "Hoferstraße",
    "Ötzfeldstraße",
    "Schönerting",
    "Schönertinger Straße",
    "Kriestorfer Straße",
    "Bräustraße",
    "Gainstorfer Straße",
    "Galgweiser Straße",
    "Malerweg",
    "Arthur-Brasgalla-Steig",
    "Glockenstraße",
    "Hedwigstraße",
    "Konradstraße",
    "Georgstraße",
    "Valentinweg",
    "Holländerstraße",
    "Stantlerstraße",
    "Moosau",
    "Oberiglbach",
    "Otto-Bohnert-Straße",
    "Mühlgasse",
    "Dr.-Vogt-Straße",
    "Edelfeldstraße",
    "Friedhofweg",
    "Eckmühlstraße",
    "Oed",
    "Voglöd",
    "Georg-Kölbl-Steg",
    "Fischhaus",
    "Zum Gewerbering",
    "Wegscheider Straße",
    "Mahd",
    "Sagmühle",
    "Kirchenplatz",
    "Reitergaßl",
    "Sankt-Gertraud-Platz",
    "Steinberg",
    "Steinmühle",
    "Siemensparkplatz",
    "Taubenberg",
    "Hochlohe",
    "Drossingweg",
    "Hasenweg",
    "Rehweg",
    "Fasanenweg",
    "Schlott",
    "Freyunger Straße",
    "Edlhofstraße",
    "Ziehweg",
    "Franz-Weismann-Straße",
    "Industriestraße",
    "Egglhamer Straße",
    "Totenweg",
    "Frauenhofer Straße",
    "Brünnlweg",
    "Banzaunstraße",
    "Steinbruchweg",
    "Georg-Knon-Straße",
    "Büchlberger Straße",
    "Am Hollerweiher",
    "Jagerweg",
    "Kirchfeldstraße",
    "Am Sportfeld",
    "Ahornweg",
    "Am Schmidfeld",
    "Frankldorfer Straße",
    "Franklbachstraße",
    "Am Praßberg",
    "Am Weiher",
    "Kirchstraße",
    "Gewerbestraße",
    "Höllstraße",
    "Goldener Steig",
    "Feldstraße",
    "Lichtenauer Straße",
    "Bäckerfeldweg",
    "Kieslingstraße",
    "Anglstraße",
    "Reuthstraße",
    "Am Klärwerk",
    "Oberer Bruennlweg",
    "Kiesling",
    "Limbach",
    "Oberilzmühle",
    "Eggersdorf",
    "Kinsing",
    "Georg-Pfeffer-Straße",
    "Kieslsteig",
    "Bachleithe",
    "Ludwig-Weinzierl-Straße",
    "Ludwig-Weinziert-Straße",
    "Am Kirchplatz",
    "Korbingasse",
    "Jägeröd",
    "Kronawitten",
    "Haag",
    "Matthias-Klinger-Straße",
    "Kreuzstöckl",
    "Marterlweg",
    "Bachwiese",
    "Am Bergholz",
    "Eisweg",
    "Götzendorfer Straße",
    "Lichtenöd",
    "Untersimboln",
    "Weihermühle",
    "Schwarzmühle",
    "Gstöttmühle",
    "Willhartsberg",
    "Kienzlmühle",
    "Wurmeck",
    "Euzersdorf",
    "Hütten",
    "Stadionstraße",
    "Mühlstraße",
    "Lindau",
    "Hallerstraße",
    "Kleinfelden",
    "Auhäusl",
    "Leitzing",
    "Hofstetten",
    "Leitenfeld",
    "Graberweg",
    "Breiteichweg",
    "Hans-Wasner-Straße",
    "Pfarrer-Reis-Straße",
    "Eggersdorfer Straße",
    "Unteres Bergfeld",
    "Am Säumerberg",
    "Am Sonnenhang",
    "Schulweg",
    "Im Tiergarten",
    "Oberes Bergfeld",
    "Taxberg",
    "Erlet",
    "Stephanstraße",
    "Neppersdorf",
    "Flenklweg",
    "Stockerfeld",
    "Weidenberg",
    "Jägerwirth",
    "Sandten",
    "Schloßweg",
    "Kreuzäcker",
    "Reitmeierfeld",
    "Pfarrer-Strohhammer-Straße",
    "Zoderweg",
    "Oberreith",
    "Rosenberg",
    "Eden",
    "Neudöbl",
    "Beutelsbacher Straße",
    "Garhamer Straße",
    "Krummaustraße",
    "Modlerstraße",
    "Max-Matheis-Straße",
    "Ludwig-Schmidseder-Straße",
    "Martin-Luther-Straße",
    "Goldberg",
    "Odilostraße",
    "Krachenberger Weg",
    "Gärtnerweg",
    "Dr.-Eireiner-Straße",
    "Feldweg",
    "Eichetstraße",
    "Reisacher Weg",
    "Kreuzbergstraße",
    "Max-Peinkofer-Straße",
    "Wimberger Straße",
    "Grünweg",
    "Untere Bachstraße",
    "Schwenghammer Straße",
    "Fisching",
    "Am Steingraben",
    "Pichlstraße",
    "Am Dobl",
    "Machelmstraße",
    "Lupinenweg",
    "Dominiweg",
    "Falkenstraße",
    "Habichtstraße",
    "Bussardstraße",
    "Rohrdommelweg",
    "Schwanenweg",
    "Eisvogelweg",
    "Bromberg",
    "Schopperweg",
    "Alte Innstraße",
    "An der Roßschwemme",
    "Kappel",
    "Bärnlochweg",
    "Waldkirchener Straße",
    "Marktstraße",
    "Bahnhofsiedlung",
    "Langer Straße",
    "ehem. Bahnstrecke Erlau–Wegscheid",
    "Kohlstattstraße",
    "Gollnerbergstraße",
    "Kaltenecker Straße",
    "Allmunzener Straße",
    "Erlbachweg",
    "Bauerngasse",
    "Malgertham",
    "Malgertsham",
    "Maierhof",
    "Künstlersteig",
    "Zieglmeisterweg",
    "Donaustraße",
    "Obere Kreppe",
    "Kapellenberg",
    "Hartham",
    "Pfistererberg",
    "Bürgermeister-Dischler-Straße",
    "Bachweg",
    "Steinkart",
    "Bürgermeister-Lindinger-Straße",
    "Am Brunnenplatzl",
    "Kellerberg",
    "Mitterham",
    "Von-Gugler-Weg",
    "Ludwigpromenade",
    "Bräuhausplatz",
    "Landrichterstraße",
    "Edelweißstraße",
    "Weghof",
    "Pater-Kolb-Weg",
    "Alfred-Kubin-Straße",
    "Niederharter Straße",
    "Gaißaweg",
    "Gramming",
    "Pestalozziring",
    "Schlesierstraße",
    "Banatweg",
    "Ausbachweg",
    "Egerlandstraße",
    "Zell",
    "Kiefernstraße",
    "Dr.-Karl-Weiß-Platz",
    "Siebenbürgenstraße",
    "Am Ferlgarten",
    "Prof.-Baumgartner-Straße",
    "Bgm.-Stoffel-Straße",
    "Franz-Xaver-Brunner-Straße",
    "Prälat-Mühldorfer-Straße",
    "Am Lindenfeld",
    "Am Höhenring",
    "Südend",
    "Max-Eyth-Straße",
    "Aunhamer Weg",
    "Vicusweg",
    "Gabingerweg",
    "Am Burgerfeld",
    "Pfarrhofweg",
    "Abt-Marius-Weg",
    "Weweckleite",
    "Holzbach",
    "Franz-Stelzhamer-Straße",
    "Ludwig-Thoma-Straße",
    "Sieglmühlweg",
    "Gföhret",
    "Endau",
    "Irsham",
    "Gruberfeld",
    "Ganghofer Straße",
    "Anzengruberstraße",
    "Wolfgang-Marius-Straße",
    "Herzog-Georg-Straße",
    "Vilsvorstadt",
    "Zellauerweg",
    "Wolfgang-Marius-Weg",
    "Pfenningbacher Straße",
    "Machham",
    "Gosting",
    "Perling",
    "Gastering",
    "Brünnerstraße",
    "Dr.-Feldbauer-Straße",
    "von-Braun-Straße",
    "Hopfenberg",
    "Rabotoweg",
    "Seestettener Straße",
    "Minihofstraße",
    "August-Wieschemeyer-Straße",
    "Johann-Baptist-Modler-Weg",
    "Max-Peinkofer-Weg",
    "Nibelungenstraße Straße",
    "Pirkinger Straße",
    "Kafferdinger Straße",
    "Am Kirchenfeld",
    "Am Tannenfeld",
    "Erlenweg",
    "Am Steinberg",
    "Birkenstraße",
    "Wiederleiten",
    "Dorfweg",
    "Brückenstraße",
    "Grundacker",
    "Rühlweg",
    "Zum Fernblick",
    "Gärbachstraße",
    "Rohrwiese",
    "Ruchtastraße",
    "Unterkogl",
    "Lohwaldstraße",
    "Oberkaining",
    "Bürgermeister-Riedl-Straße",
    "Witzling",
    "Hangerleite",
    "Schindlweg",
    "Rotbrunnweg",
    "Brunnacker",
    "Martinstraße",
    "Pfarrer-Schiermeier-Straße",
    "Langacker",
    "Karl-Mayerhofer-Straße",
    "Föhrenstraße",
    "Buchenweg",
    "Ebenthaler-Straße 1-31 b",
    "Spitzenberger Straße",
    "Rosenweg",
    "Lindbergweg",
    "Karl-Heinz-Barth-Straße",
    "Bürgermeister-Jungwirth-Straße",
    "Kurzenweg",
    "Ebenthaler Straße",
    "Kloferweg",
    "Gramletstraße",
    "Bergfeld",
    "Brunnweg",
    "Alter Fuhrweg",
    "Steinwies",
    "Am Riedlacker",
    "Granitweg",
    "Zum Alten Sportplatz",
    "Lehenstraße",
    "Gartenweg",
    "Am Hochberg",
    "Weidweg",
    "Haselberg",
    "Alter Weg",
    "Leitenweg",
    "Haarhausstraße",
    "Buchleiten",
    "Einzenberger Straße",
    "Max-Heynen-Straße",
    "Weiherweg",
    "Apothekenweg",
    "Pretzer Straße",
    "Bergfeldstraße",
    "Bayerwaldring",
    "Am Hopfengarten",
    "Hans-Habereder-Straße",
    "Posthalterstraße",
    "Am Blümersberg",
    "Färbergasse",
    "Erlenstraße",
    "Sonnenwaldstraße",
    "Siebenhasen",
    "Am Reuthölzl",
    "Sommerweide",
    "Am Alten Schulhaus",
    "Ilztalstraße",
    "Theodor-Heuss-Straße",
    "Jägersteig",
    "Grafenring",
    "Durheimer Straße",
    "Reitbauerstraße",
    "Blumenthalstraße",
    "Fasanengasse",
    "Höchfeldner Weg",
    "Untereichet",
    "Aivoglweg",
    "Am Mühlbach",
    "Aussichtstreppe",
    "Johannes-Schletterer-Weg",
    "Hartwigstraße",
    "Imbacherstraße",
    "Pfalsauer Weg",
    "Lindental",
    "Kalvarienberg",
    "Kellerfeldstraße",
    "Fasanerie",
    "Häuslinger Straße",
    "Uttigkofener Straße",
    "Brunnhäuslweg",
    "St.-Othmar-Straße",
    "Auweg",
    "Leipziger Straße",
    "Osterhofener Straße",
    "St.-Englmar-Straße",
    "Englburger Straße",
    "Stinglmühle",
    "Niederkümmering",
    "Kriemhildstraße",
    "Leharweg",
    "Bergfried",
    "Kirchgasse",
    "Innstadtbahnhofweg",
    "Reutfellnerstraße",
    "Ilzweg",
    "Fischergäßchen",
    "Lenckweg",
    "Ebenäckerring",
    "Ameisbergstraße",
    "Oberaign",
    "Marterberg",
    "Pufferholzweg",
    "Fischmarktgasse",
    "Marktgasse",
    "Meistergasse",
    "Gärtnerstraße",
    "Aidenbacher straße",
    "Am Moserweiher",
    "Schnellhamer Straße",
    "Richtsfeldstraße",
    "Holzbacher Straße",
    "Vogelkundeweg",
    "Silverioring",
    "Niederneureuth",
    "Treidlerweg",
    "Fischerweg",
    "Kalkofenweg",
    "Pointweg",
    "Am Kalvarienberg",
    "Richard-Miller-Straße",
    "Viehdurchlaß",
    "Hibingerstraße",
    "Heidwiestraße",
    "Heidwiesstraße",
    "Hofgartenweg",
    "Weweck",
    "Nikolaus Ragaller Weg",
    "Kieswerk Schlupfing",
    "Anton-Springer-Straße",
    "Schindlhofweg",
    "Stiblerweg",
    "Florianstraße",
    "Stadlöd",
    "Mitterreuthen",
    "Pollweg",
    "Pandurenweg",
    "Kleeberg",
    "Stauseestraße",
    "Holunderweg",
    "Pfründestraße",
    "Hinterbergstraße",
    "Pfarrhofstraße",
    "Fürstweg",
    "Marienstraße",
    "Hochfeld",
    "Taufkirchner Weg",
    "Moosacker",
    "Thierhamer Straße",
    "Angloh",
    "Egglfinger Straße",
    "Eichenfeld",
    "Am Tonfeld",
    "Höchfeldener Straße",
    "Thyrnau Straße",
    "Anetzbergerhof",
    "Franz-Wandl-Straße",
    "Innerreut",
    "Außernreut",
    "Dr.-Mayerhausen-Straße",
    "Forchheimerstraße",
    "Hafnergasse",
    "Rosensteig",
    "Ilzleite",
    "Kastenreuth",
    "Mooswiese",
    "Reinhold-Koeppel-Straße",
    "Ploeckensteinstraße",
    "Schreinerbauerweg",
    "Josef-Oswald-Straße",
    "Anton-Sickenberger-Straße",
    "Marquartstraße",
    "Laimgrub",
    "Plöckensteinstraße",
    "Dreisesselweg",
    "Erdbrüst",
    "Zufahrt St.-Severin-Schule",
    "Neue Schulbergstraße",
    "Am Högl",
    "Walchergasse",
    "Dr.-Fritz-Ebbert-Straße",
    "Dr.-Karl-Fuchs-Straße",
    "Harter Steig",
    "Luisenburgstraße",
    "Pfarrer-Zacher-Weg",
    "Kirschbreitenweg",
    "Holzhäuserstraße",
    "Alte Poststraße",
    "Kramersdorf",
    "Bäckerreuth",
    "Schmiedhang",
    "Akitastraße",
    "Gotthardstraße",
    "Johann-Nepomuk-Straße",
    "Sophienstraße",
    "Am Wimhof",
    "Gunthersteig",
    "Plantage",
    "Laurentiusstraße",
    "Gertraudstraße",
    "Sebastianstraße",
    "Klausenweg",
    "Fürstenweg",
    "Agnesweg",
    "Alte Rieser Straße",
    "Ludwigssteig",
    "Gampertsteig",
    "Oberer Längsweg",
    "Bussteig 5",
    "Franz-Mader-Straße",
    "Am Deglweiher",
    "Benno-Hubensteiner-Straße",
    "Sumperweg",
    "Lindenbergweg",
    "Oberhaus",
    "Parkplatz Staedt. Musikschule",
    "Graf-Leuchtenberg-Weg",
    "Mühlengasse",
    "Reutweg",
    "Reutholzweg",
    "Von-Kramer-Straße",
    "Andreas-Stahl-Straße",
    "Simbolner Gasse",
    "Oberöder Weg",
    "Leoprechtinger Straße",
    "Kleeham",
    "Stempmuehle",
    "Aufstieg Oberhaus über Wehrgang",
    "Kirchenberg",
    "Sonnleite",
    "Lebersberger Feld",
    "Lerchenfeld",
    "Lebersberger Straße",
    "Landirn",
    "Langfeld",
    "Lebersberg",
    "An der Blaiche",
    "Richtung Zolling",
    "Ilzstraße",
    "Mitterberg",
    "Grabling",
    "Richtung Kleinthannensteig",
    "Lenzersdorf",
    "Am Gewerbepark",
    "Paul-Friedl-Straße",
    "Emerenz-Meier-Straße",
    "Gumpertinger Straße",
    "Thüringer Straße",
    "Schwester-Ursinella-Platz",
    "Scherlweg",
    "Kreuzsäulenweg",
    "Nottau",
    "Jacking",
    "Hochholzweg",
    "Dietrich-Bonhoefer-Straße",
    "Aulinger Straße",
    "Am Weiherberg",
    "Am Vogeltend",
    "Schlossbergweg",
    "Hördt",
    "Auenweg",
    "Zellinger Straße",
    "Petermuellerweg",
    "Gottinger Straße",
    "Lindenhöhe",
    "Jochamstraße",
    "Einberg",
    "Bgm.-Hermann-Fisch-Straße",
    "Oberdiendorf",
    "Tiemostraße",
    "Donauweg",
    "Höflein",
    "Unterdietzing",
    "Thanöd",
    "Sturmsölden",
    "Verbindungsweg Ilzleite - Bramerhof",
    "Herzog-Albrecht-Straße",
    "Oberschöllnacher Straße",
    "Karlinger Straße",
    "Aldersbacher Straße",
    "Am Grünholz",
    "Hauptweg",
    "Dobl",
    "Naglbauer",
    "Leitendobl",
    "Pfarrer-Deindl-Straße",
    "Mühlbachstraße",
    "Fährweg",
    "Müllnerweg",
    "Brunndobl",
    "Josef-Pöltl-Weg",
    "Herrenwiese",
    "Josef-Poeltl-Weg",
    "Am Kellerberg",
    "Am Bergacker",
    "Große Messergasse",
    "Ebernäckerring",
    "Am Postberg",
    "Am Ponzaun",
    "Pfarrer-Schwarzbauer-Straße",
    "Verbindungsweg Bramerhof - Stromlänge",
    "Am Bäckerholz",
    "Stromlänge",
    "Pflegergasse",
    "Pustetweg",
    "Pfarrer-Einberger-Weg",
    "Trasham",
    "Gschwendthannet",
    "Muffatstraße",
    "Joseph-Haydn-Straße",
    "Am Schreinerfeld",
    "Wechselpergerstraße",
    "Bürgermeister-Nöbauer-Straße",
    "Irminswindstraße",
    "Unterm Berg",
    "Wilhelmstraße",
    "Enzianstraße",
    "Herzog-Ludwig-Straße",
    "Am Ziegelstadelberg",
    "Am Kirchfeld",
    "Müllerland",
    "Hübinger Straße",
    "Oberhaselbach",
    "Duringer Straße",
    "Möging",
    "Sittenberg",
    "Krehwinkel",
    "Leithener Feld",
    "Danglöder Weg",
    "Sittenberg Nr. 34-38",
    "Peter-Griesbacher-Weg",
    "Birkastraße",
    "Thanneter Straße",
    "Leithenweg",
    "Weidwiesweg",
    "Ederlsdorf",
    "Kugelholzstraße",
    "Leopoldsdorf",
    "Grub",
    "Hochreut",
    "Gruber Straße",
    "Mitterfeld",
    "Öd",
    "Hinterweg",
    "Klangfeld",
    "Klangweg",
    "Grünberg",
    "Michal-Jörg-Straße",
    "Pimmerling",
    "Pfarrer-Nömeier-Weg",
    "Burgstall",
    "Hans-Nagl-Straße",
    "Am Vogelberg",
    "Am Anger",
    "Thalhamer Weg",
    "Halmöd",
    "Kronholzer Straße",
    "Altenmarkt",
    "Dachsbergstraße",
    "Weideneckerstraße",
    "Gutwieserstraße",
    "Aubachstraße",
    "Neuhäuser",
    "Steinastraße",
    "Bajuwarenweg",
    "Hubert-Haider-Straße",
    "Harter Straße",
    "Am Innfeld",
    "Dr.-Dachsberger-Straße",
    "Josef-Starkl-Straße",
    "Leonhardiweg",
    "Alte Schulstraße",
    "Bucklmühle",
    "Gänshaller Straße",
    "Kornblumenweg",
    "Franz-Schildhammer-Straße",
    "Hausergasse",
    "Unterer Steig",
    "Mitterlinger Weg",
    "An der Ilz",
    "Baumäcker",
    "Hofäckerweg",
    "Gernäcker",
    "Auberger Straße",
    "Tragenreuth",
    "Kühweg",
    "Hangetweg",
    "Breitäcker",
    "Audobelring",
    "Ehrholzweg",
    "Schmiedeweg",
    "Barbarastraße",
    "Schachtstraße",
    "Kinderheim",
    "Heckerweg",
    "Fliederstraße",
    "Kollersberger Straße",
    "Röhrendobl",
    "Wurzenweg",
    "Zum Klättling",
    "Röhrenwiesen",
    "Knappenweg",
    "In den Breiten",
    "Vierhaupterstraße",
    "Steigerweg",
    "Hauerweg",
    "Hörmannsdorf",
    "Waldsiedlung",
    "Schwanthaler Straße",
    "Zum Reitholz",
    "Am Haarland",
    "Kleinfeldstraße",
    "Am Innspitz",
    "Aigener Straße",
    "Am Kreuzlandl",
    "Mittelstraße",
    "Am Goldenen Steig",
    "Prügelweg",
    "Birgmeierweg",
    "Bibereckerweg",
    "Haberleitenstraße",
    "Asperreutherweg",
    "Unterer Alleenweg",
    "Freudenhain",
    "Ludwigshöhe",
    "Kühberg",
    "Am Erlenbach",
    "Sturmbergweg",
    "Bockhof",
    "Bockhofweg",
    "Klafterbrunnenweg",
    "Meierweg",
    "Pilslgasse",
    "Raiffeisenweg",
    "Kelberger Weg",
    "Englboldsdorf",
    "Rußöd",
    "Watzmannsdorf",
    "Baderring",
    "Schönblick",
    "Ambrosmühl",
    "Fronhamerstraße",
    "Eichbergring",
    "Schachlöd",
    "Postberg",
    "Hochkreuzbergstraße",
    "Benediktinerweg",
    "Straßfeldwweg",
    "Leopoldsruh",
    "Pimsöd",
    "Schlehenweg",
    "Schöchlöd",
    "Pfarrer-Obermeier-Straße",
    "Adolph-Kolping-Straße",
    "Raimund-Kreuzer-Straße",
    "Dr.-Wilhelm-Löffler-Straße",
    "Am Galgenberg",
    "Max-Fraunberger-Straße",
    "Pattenhammer Höhe",
    "Zum Radler",
    "Tulpenweg",
    "Fichtenweg",
    "Steinleitnerweg",
    "Brunnfeld",
    "Neufelserstraße",
    "Graf-Heinrich-Straße",
    "Dr.-Caspar-Wimmer-Straße",
    "Anderlwies",
    "Sillerfeld",
    "Leuchtenbergstraße",
    "Steinackerstraße",
    "Flurstraße",
    "Haidenburgring",
    "St.-Wolfgang-Straße",
    "Dr.-Anton-Mayer-Straße",
    "Uttlauer Weg",
    "Sommerauweg",
    "Schratzenberg",
    "Am Pfarrfeld",
    "Ortspitze",
    "Innkai",
    "Eiching",
    "Am Kastenfeld",
    "Schmiedfeld",
    "Graf-Tiemo Straße",
    "Mitterfeldstraße",
    "Parksiedlung",
    "Karl-Sanladerer Straße",
    "Dr.-Duisberg Straße",
    "Abt-Ponigl Straße",
    "Jäger-Bartl Weg",
    "Steinbrunn",
    "Kreuzwiesenweg",
    "O.-Berneder-Ring",
    "Hofwiesen",
    "Mairau",
    "Voglmühle 8-10",
    "Rumpernfeld",
    "Lange Gasse",
    "Schönaustraße",
    "Blumenau",
    "Hauskramerfeld",
    "Alter Steig",
    "Königsdobl",
    "Am Glauberg",
    "Striglerweg",
    "Säumergasse",
    "Blütenweg",
    "Kreuzstraße",
    "Riedenburger Weg",
    "Rennstattweg",
    "Aichmühlweg",
    "Alois-Fürst-Straße",
    "Stocklandweg",
    "Hindlbachstraße",
    "Schalterner Straße",
    "Siedlungsring",
    "Lerchenstraße",
    "Baron-von-Behr-Straße",
    "Franz-Straßer-Straße",
    "Hochwies",
    "Zum Rohrmeier",
    "Hitzling",
    "Algerting",
    "Maierholzstraße",
    "Hans-Penninger-Straße",
    "Blumentalweg",
    "Max-Wimmer-Ring",
    "Laborantenweg",
    "Binderstraße",
    "Gänswinkl",
    "Jägermühle",
    "Pfarrer-Hannes-Straße",
    "Bischof-Gottfried-Straße",
    "Mitterfeldweg",
    "Aufeld",
    "Scheuereck",
    "Haydnweg",
    "Abt-Walther-Straße",
    "Königbacher Straße",
    "Alte Schulweg",
    "Hofmannsthalstraße",
    "Oberöd",
    "Unteröd i.Ilztal",
    "Unterjacking",
    "Am Oberfeld",
    "Thal",
    "Turmweg",
    "Schwaiberger Straße",
    "Hof",
    "Pilgrimstraße",
    "Sünzlweg",
    "Pfarrer-Böck-Straße",
    "Allertinger Straße",
    "Söldenweg",
    "Am Hofacker",
    "Am Kieswerk",
    "Allerting",
    "Haltestelle",
    "Ebersbergerstraße",
    "Ottokarstraße",
    "Sulzsteg",
    "Hammerberg",
    "Alte B388",
    "Weberhanslgasse",
    "Orchideenweg",
    "Niglstraße",
    "Oberkogl",
    "Josef-Erner-Straße",
    "Kirchholzweg",
    "Am Rastfeld",
    "Bärenholzweg",
    "Scheiblweg",
    "Am Bach",
    "Maria-Stockbauer-Weg",
    "Kaiserweg",
    "Osserstraße",
    "Matthias-Koller-Straße",
    "Altreuthweg",
    "Rudolf-Töpfl-Straße",
    "Hochstiftsweg",
    "Siedlerweg",
    "Alois-Zwislsberger-Straße",
    "Anna-Knott-Straße",
    "Georg-Fraunhofer-Straße",
    "Georg-Kühberger-Straße",
    "Josef-Fruth-Straße",
    "Alois-Muttenhammer-Straße",
    "Pfarrer-Matschl-Weg",
    "Max-Reschauer-Straße",
    "Hörmannsberg",
    "Burgholz",
    "Kleinfeldweg",
    "Schlossweg",
    "Hofgarten",
    "Amersberg",
    "Ödbrunnenweg",
    "Hölzlweg",
    "Am Bergl",
    "Bründlweg",
    "Am Geiersberg",
    "Bachfeldweg",
    "Am Scheuwelhölzl",
    "Gehersberger Straße",
    "Fichtenstraße",
    "Schwarzensteiner Weg",
    "Geisbergweg",
    "Windpassing",
    "Eck",
    "Donaugründe",
    "Dr. Hans-Vogt-Platz",
    "Dr.-Hans-Vogt-Straße",
    "Bahnhof Schaibing",
    "Niedersatzbach",
    "Am Brunnanger",
    "Birkenanger",
    "Ahornstraße",
    "Hagenhamer Straße",
    "Neumühle",
    "Metzgerwegerl",
    "Blumenweg",
    "Am Holleracker",
    "Florianweg",
    "Ritzging",
    "Bichlberger Straße",
    "Holzhof",
    "Burgstallweg",
    "Stelzlhof",
    "Kringeller Straße",
    "Hundsruck",
    "Alztalgasse",
    "Ostring",
    "Westring",
    "Neubürgerstraße",
    "Heuweg",
    "Witzingerreuter Straße",
    "Scharbachweg",
    "Oberer Steinweg",
    "Hofstraße",
    "Röhrengasse",
    "Freihofer Straße",
    "Carl-Kerber-Straße",
    "Auretzdorf",
    "Gottfried-Schäffer-Straße",
    "Lehranstalt Kringell",
    "Kringell",
    "Heumahderweg",
    "Rennweg",
    "Lederer-Straße",
    "Färber-Straße",
    "Kupferschmied-Straße",
    "Tuchmacher-Straße",
    "Oberkarlinger Straße",
    "Leinberger-Straße",
    "Dekan-Haydn-Weg",
    "Ulmenweg",
    "Sendlingerstraße",
    "Hollerbacher Straße",
    "Schwester-Festa-Straße",
    "Kleebergstraße",
    "Doblbauer Straße",
    "Jos.-Willmerdinger-Straße",
    "Vivilostraße",
    "Sigmundt-Münch-Straße",
    "Schwaigstraße",
    "Kantnerstraße",
    "Mondseestraße",
    "Tremmelstraße",
    "Residenzstraße",
    "Asam-Ring",
    "Schwarzholz",
    "Stockcarbahn Aldersbach",
    "Georg-Graml-Straße",
    "Rudolf-von-Scholtz-Straße",
    "Albert-Lucas-Straße",
    "Mausmühle",
    "Heilikastraße",
    "Hartkirchener Straße",
    "Am Gänseacker",
    "Reihenweg",
    "Weichselgasse",
    "Metzgerstraße",
    "Fichtensteg",
    "Steinbacherweg",
    "Meisterweg",
    "Wührerweg",
    "Fuchswirtsweg",
    "Bachmoserweg",
    "Hufnaglweg",
    "Kohweg",
    "Schusterpoint",
    "Göschlweg",
    "Heilmühlerweg",
    "Wastlbauerweg",
    "Brunnerweg",
    "Schreinerweg",
    "Stockweg",
    "Graswinkelstraße",
    "Dammweg",
    "Am Steinbergerfeld",
    "Obere Bachstraße",
    "Lilienweg",
    "Am Schachen",
    "Sickingergasse",
    "Kopernikusring",
    "Asperweg",
    "An der Kapelle",
    "An der Schule",
    "Am Wolfseck",
    "Sonneneck",
    "Schiffergasse",
    "Quellengasse",
    "Am Gaßl",
    "Donauhof",
    "Reuthweg",
    "Zur Höll",
    "Am Nanzelberg",
    "Schusterweg",
    "Am Binderberg",
    "Kresslingweg",
    "Ungarsteig",
    "Bruckweg",
    "Reutlweg",
    "Hirschenbergweg",
    "Reithbergweg",
    "Obere Inntal Straße",
    "Raumreuth",
    "Pfeifferweg",
    "Am Gegenbach",
    "Pfeiferweg",
    "Schönberghäuser",
    "Spiesbrunnweg",
    "Am Schönberg",
    "Drexlerwiese",
    "Klaus-Dieter-Kindl-Platz",
    "Fritz-Schramm-Ring",
    "Am Birkenweg",
    "Holzgattern",
    "Schönwiese",
    "Binderhügel",
    "Mannhäuserweg",
    "Schöllingerweg",
    "Brunnenwiesen",
    "Thalberg am Badeweiher",
    "Voggenberger Weg",
    "Siegfriedstraße",
    "Unteröd im Ilztal",
    "Moos",
    "Oberneureuther Straße",
    "Kühbergstraße",
    "Sunninger Weg",
    "Sicklinger Weg",
    "Roßau",
    "Kappelgartenstraße",
    "Hochwurzweg",
    "Hochwurz",
    "Hofacker",
    "Wastlweg",
    "Ehrdobelweg",
    "Pfaffenreuth",
    "Straßerweg",
    "Zur Au",
    "Am Breitacker",
    "Moosweg",
    "Ziegelweg",
    "Hollergasse",
    "Am Aufeld",
    "Siedlung",
    "Birkfeld",
    "Knappenstraße",
    "Flurwiesenweg",
    "Burgstallstraße",
    "Bergweg",
    "Am Wassergraben",
    "Zellergasse",
    "Flurbereinigungsstraße",
    "Kühbachäcker",
    "Garmer Straße",
    "Steinmühl",
    "Badgasse",
    "Am Dorfbach",
    "Riedler Straße",
    "Reitgasse",
    "St.-Jakob-Straße",
    "Donausteig",
    "Hoffeld",
    "Glotzing",
    "Oberlehrer-Haiböck-Straße",
    "Eckhofkeller",
    "Duschlbergstraße",
    "Seiboldwies",
    "Am Fürstberg",
    "Am Säumertor",
    "Burgweg",
    "Am Bad",
    "Zaunbrechl",
    "Am Bahndamm",
    "Buchetweg",
    "Hofackerweg",
    "Unteres Mitterfeld",
    "Oberes Mitterfeld",
    "Hofwiesenweg",
    "Gerstenweg",
    "Weiherfeldstraße",
    "Rauchweg",
    "Hunabergstraße",
    "Thießenweg",
    "Kreuzwiese",
    "Hochreutweg",
    "An der Bleiche",
    "Ahndlweg",
    "Bruckbachweg",
    "Sommerberg",
    "Raßberg",
    "Oberholz",
    "Kronreuth",
    "Furtfeld",
    "Ritter von Scheuring Straße",
    "Granitstraße",
    "Schadweg",
    "Kussersiedlung",
    "Felsenweg",
    "Im Winkel",
    "Döbling",
    "Alte Waldkirchener Straße",
    "Am Waldsteig",
    "Pufferholz",
    "Am Waldeck",
    "Steinäcker",
    "Steinfeld",
    "Dr.-Ludwig-Veit-Weg",
    "Hirtenweg",
    "Hohlweg",
    "Talstraße",
    "Oberpretz",
    "Germannsbergstraße",
    "Wanderweg Nr. 2 + 4",
    "Wanderweg Nr. 2",
    "Ziegeleiweg",
    "Prager Schulstraße",
    "Ganslbachstraße",
    "Forellenweg",
    "Karpfenweg",
    "Wehrgang",
    "Am Hafnerfeld",
    "Seestraße",
    "Steinhauerweg",
    "Steinhauerstraße",
    "Alte Gasse",
    "Am Klosterfeld",
    "Friedhofsteig",
    "Bgm.-Kainz-Straße",
    "St.-Blasius-Straße",
    "Am Belvedere",
    "Am Breinhof",
    "Am Lohhaufen",
    "Bäckergäßchen",
    "Steinhubergasserl",
    "Gundackerstraße",
    "Erhardstraße",
    "Bacheröd",
    "Wirtsholz",
    "Böcklbacher Straße",
    "Altenöd",
    "Am Laimacker",
    "Am Pointacker",
    "Pleckental",
    "Altenödweg",
    "Libellenweg",
    "Blumental",
    "Riegerödweg",
    "Weißenfelderstraße",
    "Stadtberg",
    "Dr.-Winklhofer-Straße",
    "Falkenweg",
    "Stockbauersteig",
    "Maria-Uhrmann-Straße",
    "Müllerweg",
    "Max-Mattheis-Straße",
    "Hochweg",
    "Petzersberger Straße",
    "Kirchweg",
    "Am Südhang",
    "Joseph-Saam-Straße",
    "Max-Tremmel-Straße",
    "Wilhelm-Pöll-Straße",
    "Walter-Hornsteiner-Straße",
    "Walther-Schuster-Straße",
    "Hermann-von-Moreau-Straße",
    "Koglring",
    "Prager Straße",
    "Triftsperrstraße",
    "Rosenauer Weg",
    "Deglgasse",
    "Am Kirschgarten",
    "Augut",
    "Kaltschmidtgasse",
    "Hochlandweg",
    "Hofingerweg",
    "Innstadtkellerweg",
    "Pramöd",
    "Doblhof",
    "Grillenöd",
    "St.-Peter-Straße",
    "Heinrichstraße",
    "Nikolasstraße",
    "Am Kapellenfeld",
    "An der Keltenschanze",
    "Haar",
    "Schömerweg",
    "Karlmann",
    "Zwinger",
    "St.-Agatha-Weg",
    "Dekan-Schneid-Weg",
    "Vilserstraße",
    "Heidfeldstraße",
    "Angerweg",
    "Unterreit",
    "Kehrwisching",
    "Mattenhamer Brücke",
    "Mattenhamer Straße",
    "Heckenweg",
    "Stieglitzweg",
    "Haselweg",
    "Zu den Weihern",
    "Am Bloberlberg",
    "Am Hinterholz",
    "Hilgartsbergweg",
    "Straßerödweg",
    "Sommerau",
    "Am Horiberg",
    "Am Bründl",
    "Am Kerschbach",
    "Grubödstraße",
    "Schauberg",
    "Grüblmühle",
    "Bachhäusel",
    "Kainzöd",
    "Fürhaupt",
    "Carossaweg",
    "Sterlwaid",
    "Rothmad",
    "Duscherpoint",
    "Guppenberg",
    "Ruhmannsdorf",
    "Ebenfeldweg",
    "Flachsweg",
    "Eitzingerreut",
    "Kammerwetzdorf",
    "Bautacker",
    "Hunaberg",
    "Im Dorf",
    "Egerstraße",
    "Hopfgartenweg",
    "In der Leiten",
    "Nußbaumweg",
    "Sannerwies",
    "Staffelhof",
    "Röhrndl",
    "Urtelweg",
    "Unterfeldweg",
    "Hinterfeld",
    "Südhang",
    "Hochhausstraße",
    "Kirchhofweg",
    "Brünststraße",
    "Innerhartsberg",
    "Graphitweg",
    "Knappenhäusl",
    "PA 49",
    "Langheinrichstraße",
    "Bachwanderweg",
    "Pisling",
    "Eben",
    "Loifing",
    "Haagwieser Weg",
    "Niederbrünst",
    "Jahrdorferschacht",
    "Wastlmühlstraße",
    "Wastlmühlweg",
    "Redling",
    "Eckhofstraße",
    "Markusstraße",
    "Toni-Pötzl-Straße",
    "Vitusstraße",
    "Krinningerstraße",
    "Am Dichtlacker",
    "Piusweg",
    "Peinkoferstraße",
    "Bischof-Trennbach-Ring",
    "Schlossplatz",
    "Aubachmühle",
    "Eichenhain",
    "Hollerweg",
    "Pettenkoferstraße",
    "Roßeck",
    "Alte Schule",
    "Spiesbrunn",
    "Obere Schneckenbergstraße",
    "Werner-Diedrich-Straße",
    "Siedlerstraße",
    "Doktor-Gantenberg-Straße",
    "Bieretäckerstraße",
    "Fürstenecker Straße",
    "Hochring",
    "Kammgasse",
    "Waldgasse",
    "Alfons-Duschl-Straße",
    "Michael-Witzlinger-Straße",
    "Peter-Almer-Straße",
    "Schwaighofstraße",
    "Sepp-Kiermaier-Straße",
    "Bergmüllerstraße",
    "Jakob-Zeiller-Straße",
    "Johann-Baptist-Modler-Straße",
    "Matthias-Götz-Straße",
    "Matthäus-Günther-Straße",
    "Graf-Goder-Straße",
    "Josef-Müller-Straße",
    "Im Moos",
    "Josef-Deutschmann-Straße",
    "Sagmeistergarten",
    "Walchsinger Straße",
    "Wiflinger Straße",
    "Zisterzienser-Straße",
    "Freiherr-von-Aretin-Platz",
    "Lichtenauer Weg",
    "Elisabethstraße",
    "Herzog-Arnulf-Straße",
    "Tolnaustraße",
    "Danglmühle",
    "Schröck",
    "Edwiese",
    "Hammerschmiedstraße",
    "Bergäcker",
    "Garhamstraße",
    "Im Tal",
    "Hans-Günther-Straße",
    "Schulerbruch",
    "Muggenthaler Straße",
    "Anton-Paintner-Weg",
    "Otto-Schürzinger-Weg",
    "Pilzwegerstraße",
    "Willhelm-Millauer-Weg",
    "Sankt Bernhardsberg",
    "Abt-Fischer-Straße",
    "Altomontestraße",
    "Bischof-Otto-Straße",
    "Gebrüder-Carlone-Straße",
    "Griessemannstraße",
    "Johann-Degler-Straße",
    "Josef-Prex-Straße",
    "Kirchberger Straße",
    "Klosterplatz",
    "Magzinstraße",
    "Nikolaus-Stuber-Straße",
    "Otto-Doringer-Straße",
    "Reitwinklerstraße",
    "Sankt Peter",
    "Georg-Abröll-Straße",
    "Theobald-Grad-Straße",
    "Weng",
    "Pörndorfer Straße",
    "Schröckstraße",
    "Rothmahd",
    "Berbing",
    "Nottauer Weg",
    "Doktor-Wimmer-Ring",
    "Waldeckstraße",
    "Am Steig",
    "Edhäusl",
    "Steinmetzstraße",
    "Turnersteig",
    "Am Schulhügel",
    "Am Weinhügel",
    "Bruder-Konrad-Weg",
    "Karl-Schmidbauer-Straße",
    "Max-Köhler-Straße",
    "Oberweinzierler Straße",
    "Weinzierler Gangsteig",
    "Gießübl",
    "Oberer Gießübl",
    "Kaltrum",
    "Steinbergstraße",
    "Petzenbergstraße",
    "Grubweg",
    "Schachet",
    "Steinwall",
    "Denkbauerweg",
    "Fuchsweg",
    "Hanggasse",
    "Sölling",
    "Söllinger Straße",
    "Bahnsteig",
    "Eckmühle",
    "Schulsteig",
    "Staffelbachweg",
    "Staffelstraße",
    "Nöberweg",
    "Gallusstraße",
    "Hartstraße",
    "Niederindling",
    "Reistinger Straße",
    "Einöder Straße",
    "Kutschenreutherstraße",
    "Hoffeldweg",
    "Königschaldinger Straße",
    "Frauenberg",
    "Salzreut",
    "Am Pangerlberg",
    "Bürgermeister-Poxleitner-Straße",
    "Reitbergstraße",
    "Talweg",
    "Weihergasse",
    "Kinderheimstraße",
    "Praßreuter Straße",
    "Ulrichsheimstraße",
    "Heimweg",
    "Unterkatzendorfer Straße",
    "Weidstraße",
    "Am Rathaus",
    "Eichendorffweg",
    "Matheisweg",
    "Posthalterweg",
    "Papiermühle",
    "Bischof-Altmann-Weg",
    "Degenhartring",
    "König Max Promenade",
    "Pfarrer-Nagler-Weg",
    "Dr.-Sittler-Straße",
    "Johann-Huber-Straße",
    "Leidlstraße",
    "Am Kinsingwald",
    "Alte Hofmarkstraße",
    "Jakob-Bleyer-Straße",
    "Ludwig-Thoma-Ring",
    "Paul-Keller-Straße",
    "Perthelmstraße",
    "An der Blumenwiese",
    "Michael-Stapfer-Straße",
    "Oberindlinger Straße",
    "Rottstraße",
    "Schlupfinger Straße",
    "Bürgermeister-Fischer-Straße",
    "Gewerbepark Aunkirchen",
    "St.-Nicola-Straße",
    "Michl-Natter-Straße",
    "Watzmannsberger Straße",
    "Eduard-Poschinger-Weg",
    "Gustav-Haydn-Straße",
    "Pater-Rupert-Mayer-Straße",
    "Kapping",
    "Bucher Straße",
    "Unterbuch",
    "Furtgasse",
    "Alkofener Hauptstraße",
    "Karl-Beck-Weg",
    "Seier",
    "Kindergartenweg",
    "Fürstensteiner Straße",
    "Agilofingertstraße",
    "Matthias-Fink-Straße",
    "Dr.–Schlögl-Straße",
    "Höhenreutweg",
    "Breitenwiese",
    "Kindleinsberg",
    "Seiersdorf",
    "Stolzesberg",
    "Am Kreisel",
    "Witzersdorf",
    "Einzendoblmühle",
    "Einzendoblstraße",
    "Fälsching",
    "Thannberger Straße",
    "Albersdorfer Straße",
    "Am Eichenhain",
    "Untereginger Straße",
    "Ziegelfeldstraße",
    "Edelweißgasse",
    "Enzianweg",
    "Jasminweg",
    "Narzissenweg",
    "Nelkengasse",
    "Veilchenweg",
    "Kollmeringer Straße",
    "Spechtstraße",
    "Andreas-Seider-Straße",
    "Innerhardtsberg",
    "Manzenberg",
    "Bergholzstraße",
    "Erlauweg",
    "Hartzeitlarner Straße",
    "Hennermais",
    "Quintana Straße",
    "Alte Raiffeisenstraße",
    "Baumannstraße",
    "Kneippstraße",
    "Mautgasse",
    "Pellstraße",
    "Zum Ilztal",
    "Magalettigasse",
    "Alte Schloßstraße",
    "Neue Schloßstraße",
    "Hofstiege",
    "Maierhofbrücke",
    "Stadlergasse",
    "Apostelstraße",
    "Gothardstraße",
    "Nepomuk-Meier-Straße",
    "Kufnergasse",
    "Matthias-Klebl-Straße",
    "Dietmar-von-Ayst-Straße",
    "Kleeberger Weg",
    "Mooswiesen",
    "Schießgarten",
    "Reschenstein",
    "Oberer Alleenweg",
    "Teufelstein",
    "Jausengütlweg",
    "Jakob-Bernauer-Straße",
    "Franz-Koch-Straße",
    "Josef-Pamler-Straße",
    "Simon-Hirschvogel-Straße",
    "Anton-Haberl-Straße",
    "Feuchtmayr-Straße",
    "Gebrüder-Asam-Straße",
    "Ignaz-Günther-Straße",
    "Alter-Kirchenweg",
    "Krankenhaus-Straße",
    "Kreuzkirchenstraße",
    "Bockbauernweg",
    "Pfarrweg",
    "Pfarrer-Meisinger-Straße",
    "Am Bräuweiher",
    "Erlenweide",
    "Zur Melberöd",
    "Scheibe",
    "Kaltenöd",
    "Schneidermühl",
    "Kollerwirtsgasse",
    "Baptist-Kitzlinger-Straße",
    "Baywastraße",
    "Gründoblweg",
    "Jägerwirthsteig",
    "Jägerreuth",
    "Kuchlhof",
    "Langlebenhofweg",
    "Oberer Klosterholzweg",
    "Unterer Klosterholzweg",
    "Fattinger Straße",
    "Sturmbergfeldweg",
    "Rieshof",
    "Flieherweg",
    "Haberleitenweg",
    "Schafhof",
    "Marbachweg",
    "Emil-Richter-Straße",
    "Steppachweg",
    "Sperrwies",
    "Max-Grünbeck-Straße",
    "Kaisergasse",
    "Mittereckweg",
    "Mesnerweg",
    "Laufenbach",
    "Peilsteiner Weg",
    "Lenzenweg",
    "Schöttlweg",
    "Waldpointerweg",
    "Ramersbachweg",
    "Jägerhof",
    "Prangersteig",
    "Steinleitenweg",
    "Kohlweg",
    "Weißstraße",
    "Wiesbauerfeld",
    "During",
    "Ruderting, Buchbauer",
    "Museumstraße",
    "Kramerweg",
    "Prof.-Dr.-Schedel-Straße",
    "Weinzierler Straße",
    "Eduard-Hamm-Straße",
    "Am Plettlberg",
    "Am Magauerhof",
    "Stachl",
    "Gewerbering Fürstdobl",
    "Eckbertstraße",
    "Eckmüllergasse",
    "Sandberg",
    "Von-Thun Straße",
    "Haarstubnerweg",
    "Maueröd",
    "Am Riedlbach",
    "Von-Schrank Straße",
    "Adilgerstraße",
    "Albersdorfer Hauptstraße",
    "Albersdorfer Industriepark",
    "Aventinstraße",
    "Ernst-Hofmann-Weg",
    "Kobellstraße",
    "Kutschenreuterweg",
    "Vogteistraße",
    "Hirnschnellerweg",
    "Alois-Geisberger Straße",
    "Alois-Schober Straße",
    "Barthlmannstraße",
    "Gemeindewiese",
    "Hangweg",
    "Pfarrer-Wenninger Straße",
    "Sulzbachweg",
    "Am Bahnberg",
    "Neuhofener Straße",
    "Gewerbegebiet Hartham",
    "Schaibinger Straße",
    "Kamping",
    "Wirtsfeld",
    "Keltenring",
    "Biberger Straße",
    "Reith",
    "Kreuzweg",
    "Schwarze Säge",
    "Kapfham",
    "Steffelmühlweg",
    "Rudolf-Guby-Straße",
    "Soldatenbrunnweg",
    "Schürzingerstraße",
    "Johann-Baptist-Straub-Straße",
    "Josef-Deutschmann-Straß",
    "Blutwurzpfad",
    "Thyrnauer Straße",
    "Alter Kirchweg",
    "Unterer Längsweg",
    "Fuchsfeldstraße",
    "Am Schachlbauerfeld",
    "Raindinger Hauptstraße",
    "Zu den Auen",
    "Am Birkldobl",
    "Reitergasse",
    "Lohfeldstraße",
    "Hintere Marktgasse",
    "Rutschmannstraße",
    "Bozener Straße",
    "Pfarrer-Beham-Straße",
    "Sigfridstraße",
    "Kollbachweg",
    "Hofackerstraße",
    "Prälat_Eggersdorfer-Straße",
    "Abt-Hugo-Straſse",
    "Reinoldstraße",
    "Pfarrer-Seel-Straße",
    "Kremser Straße",
    "Kasberger Straße",
    "Pommeislhammer",
    "Hedwigsschacht",
    "Karl-Schachtner-Straße",
    "Weingärten",
    "Haarbachweg",
    "Kirchbachfeld",
    "Am Gatterltürl",
    "Am Plattel",
    "Am Kammerlberg",
    "Dr.-Schlögl-Straße",
    "Alte Bahnhofstraße",
    "Walchgasse",
    "Pfarrhofsiedlung",
    "Reifziehberg",
    "Zum Sechssessel",
    "Am Ziegelfeld",
    "Oberhausleitenstiege",
    "Oberhausleitemstiege",
    "Am Lehrerweiher",
    "Zugang zur Kirche",
    "Promenadenweg",
    "Dr.-Schindler-Straße",
    "Am Kreuzberg",
    "Kardenweg",
    "Kaiserstraße",
    "Schulgasse",
    "Puchberger Ring",
    "Franhofer Ring",
    "Am Wiesengrund",
    "An der Ohe",
    "Gewerbepark Garham",
    "Wolfenweiherweg",
    "Fichtenring",
    "Fabrikstraße",
    "Rapoloweg",
    "Am Zeisenstein",
    "Plidmunt-Weg",
    "PA-14 - Steinhuegl",
    "Nr. 4",
    "Gewerbegebiet",
    "Bgm. Wenig Straße",
    "Hainbuchenweg",
    "Schlehenstraße",
    "St.-Florian-Weg",
    "Meindlstraße",
    "Am Klosterhof",
    "Bienenweg",
    "Bürgermeister-Osterholzer-Straße",
    "Pfarrer-Biermeier-Straße",
    "Winklmanngasse",
    "Abschnitt Wanderweg 7",
    "Bayerwaldblick",
    "Bergholzweg",
    "Eitlöd",
    "Reindlöd",
    "Sieghartsmühle",
    "Marienbader Straße",
    "Humpertsauweg",
    "Berging",
    "Rottersham",
    "Mutholz",
    "Angering",
    "Haidzing",
    "Beham",
    "Bärnau",
    "Zieglöd",
    "Forststraße",
    "Holzhaus",
    "Hub",
    "Brandschachen",
    "Zwicklarn",
    "Ortsstraße",
    "Viehweid",
    "Pfarrer-Eder-Straße",
    "Pfarrer-Wasmaier-Straße",
    "Am Fichtenholz",
    "Fischerwiesen Ring",
    "Krautpoint",
    "Leiberstraße",
    "Tempelweg",
    "Zum Hochfeld",
    "Ignaz-Keil-Straße",
    "Meisenweg",
    "Auerweg",
    "Meierstraße",
    "Schmölz",
    "Kurplatz",
    "Einhausung Tutting",
    "Wieshof",
    "Motocross Vilshofen",
    "Lagerhausstraße",
    "Pfarrer-Pusch-Straße",
    "Girchingerfeld",
    "Kaiserfeld",
    "Freudenseestraße",
    "Mohnweg",
    "Rasthofstraße",
    "Gustav-Kapaun-Straße",
    "Am Pfarrgarten",
    "Joseph-Deutschmann-Straße",
    "Vikar-Golling-Straße",
    "Waltenbergerstraße",
    "Am Schlosspark",
    "An der Linde",
    "Moritzweg",
    "Unter der alten Bahnbrücke",
    "Brunnengasse",
    "Am Park",
    "Oskar-von-Miller-Straße",
    "Zugang zum Haltepunkt",
    "Karl-von-Moreau-Straße",
    "Niedere Lohe",
    "Rottalheimweg",
    "Banaterweg",
    "Caritasweg",
    "Rottershamer Kirchenweg",
    "Rappenweg",
    "Binderweg",
    "Am Kühholz",
    "Zeilbergweg",
    "Ringweg",
    "Getreidekästen",
    "Mühlenviertel",
    "unteres Dorf",
    "Ortäcker",
    "Pfarrer Kroll-Straße",
    "Kurzwiese",
    "Kornweg",
    "Donautal Ost",
    "Donautal West",
    "Reutacker",
    "Adolf-Bessel-Straße",
    "Petzenberg",
    "Müllerbleiche",
    "Ambrosweg",
    "Bräuleite",
    "Auf der Höh",
    "Am Lohstampf",
    "Brunnwiesenweg",
    "Am Rosenium",
    "Lohwiese",
    "Grünleithenweg",
    "Pröllerstraße",
    "Tassilostraße",
    "Rastplatz Jägerhölzl",
    "Zum Burgenblick",
    "Am Sonnenhügel",
    "Hösamer Straße",
    "St.-Andreas-Weg",
    "Johann-Müller-Straße",
    "Romanstraße",
    "Fohlenweideweg",
    "Wilhelm-Reitmeier-Straße",
    "Pfarrer-Lechner-Weg",
    "Am Kosmühlweg",
    "Karlstraße",
    "Am Marktacker",
    "Leuchtenbergweg",
    "Georg-Meindl-Straße",
    "Peter-Nagl-Straße",
    "Handlbergstraße",
    "Prielmayrstraße",
    "Gemmelweg",
    "Johann-Hoffmann-Straße",
    "Woichingerstraße",
    "Behelfsauffahrt",
    "Willib.-Hauer-Straße",
    "Urbanstraße",
    "Heuwiesl",
    "Steinreuther Straße",
    "Sonnenleithe",
    "Michlbauerweg",
    "Am Höhenberg",
    "Mater-Brigitta-Straße",
    "Schloßstraße",
    "Geschwister-Wenig-Ring",
    "Schießstättenweg",
    "Anna-Wasner-Straße",
    "Tiefgarage",
    "Wieslhuberstraße",
    "Martin-Prech-Straße",
    "Triftsperren Tunnel",
    "Am Schulfeld",
    "Der Beweger",
    "Turmweg 1-1b",
    "Höhenmüle",
    "Pater-Gierg-Weg",
    "Espetgasse",
    "Forstergasse",
    "Rastplatz Schaufelholz",
    "Rastplatz Eichet",
    "Rastplatz Stierwaid",
    "Rastplatz Brentermais",
    "Rastplatz Rottal-Ost",
    "Rastplatz Rottal West",
    "Doblstraße",
    "Wergandweg",
    "Am Gutshof",
    "Am Dorfplatz",
    "Rot-Kreuz-Straße",
    "Winklhof",
    "Oberer Sattlerberg",
    "Schmugglerweg",
    "Franz-Ringseis-Weg",
    "Prof.-Winklhofer-Weg",
    "Richard-Billinger-Weg",
    "Wimberger Höhe",
    "Hubert-Neufeld-Weg",
    "Peter-Rosegger-Weg",
    "Wilhelm-Diess-Weg",
    "Kleiner Rottweg",
    "Frimhöringer Straße",
    "Pfarrer-Wagner-Straße",
    "Birkethöhe",
    "Schmidhamer Straße",
    "Oberhauserleitenstiege",
    "Nikolausstraße",
    "Bischof-Hartmann-Straße",
    "Postweg",
    "Friedlandweg",
    "Auf dem Reithen",
    "Staffenöd",
    "Schrönghamerweg",
    "Kollerreuth",
    "Einöden",
    "Lößrankenweg",
    "Ziegeleigasse",
    "Professor Kirschner Straße",
    "Pfarrer-Aumüller-Straße",
    "Labyrinth am Blümersberg",
    "Von-Fraunhofer-Ring",
    "Bgm.-Gierlinger-Straße",
    "Sägeweg",
    "St.-Georg-Weg",
    "Bgm.-Birndorfer-Straße",
    "Öttl-Steig",
    "Biergarten",
    "Raßbach",
    "Zwölfling",
    "Geiersberg",
    "Obersölling",
    "Am Haselholz",
    "Am Feldanger",
    "Fußweg nach Raßreuth",
    "Unterer Gießübl",
    "Kühbach 3",
    "Danglöd",
    "Riedlöd",
    "Heigerting",
    "An der Klinge",
    "Webermannweg",
    "Hermann-Silbereisen-Straße",
    "Kuppermühlerweg",
    "Ludwig-Ganghofer-Weg",
    "Am Wababerg",
    "Kramerleithe",
    "Pulverweg",
    "Dorfgasse",
    "Bachgasse",
    "Mozartweg",
    "Riedlweg",
    "Eduard-List-Weg",
    "Fürststraße",
    "Karlinger Feld",
    "Grossthannensteig",
    "Weitfeldweg",
    "Dorfbacher Straße",
    "Am Steppbach",
    "Hoferweg",
    "Laurentiusweg",
    "Wagnerfeld",
    "MTB HERO Wegscheid",
    "Neudobl",
    "Ludwig-Huber-Gasse",
    "Am Steinfeld",
    "Veitlöd",
    "Sallingergasse",
    "Am Hammersberg",
    "Nechwatalstraße",
    "Neuhaus",
    "Gruböd",
    "Am Kramerberg",
    "Molkereistraße",
    "Glaserstraße",
    "Hellmannsberger Weg",
    "Am Mautnerhof",
    "Judenhof",
    "Birketstraße",
    "An der Bräukapelle",
    "Josef-Rädlinger-Straße",
    "Summerhofstraße",
    "Ritter-Ortolf-Straße",
    "Wochingerstraße",
    "An der Vitzthummühle",
    "Dr.-Hans-Karl-Fischer-Straße",
    "Steppenweg",
    "Reschendoblstraße",
    "Fußgängerunterführung",
    "Niederleuthnersteig",
    "Donau- Ufer- Kai",
    "Lehen",
    "Asenham",
    "Am Reutacker",
    "Grüner Weg",
    "8",
    "Oberer Mühlweg",
    "Unterer Mühlweg",
    "Paul-Vogl-Straße",
    "Hofreither Straße",
    "Mistlbacher Weg",
    "Anbindung Bauhaltestelle",
    "Am Wald",
    "Grafengaßl",
    "Strenn",
    "Hohentanner Straße",
    "Mostwanderweg",
    "Moststeig",
    "Rehgarten",
    "Am Schloßberg",
    "Emerenz-Maier-Weg",
    "Boierstraße",
    "Alter Sportplatz",
    "Hubödstraße",
    "Obere Weweckleite",
    "Am Steinbach",
    "Oberdorf",
    "Schnellham",
    "Steinmetzgaßl",
    "Primsdoblweg",
    "Arberweg",
    "Paula-Deppe-Weg",
    "Wimmstraße",
    "Schopperstraße",
    "Pandurensteig",
    "Alte Mühlweiherstraße",
    "Burgenblick",
    "Insel",
    "Am Asamblick",
    "Pater-Stefan-Straße",
    "Weizenackerweg",
    "Ernst-Heynen-Straße",
    "Maseringer Straße",
    "Am Wildenberg",
    "Rothauer Straße",
    "Oberbucher Straße",
    "Am Thannetholz",
    "Neukirchen (Inn), Bf",
    "Benediktinerstraße",
    "Tavernenweg",
    "Pfarrer-Reiter-Straße",
    "Pfarrer-Hartl-Straße",
    "Kleiberweg",
    "Julbachstraße",
    "Ledererstraße",
    "Wiesensteig",
    "Arbingerstraße",
    "Arbing",
    "Panholzstraße",
    "Bad Höhenstadt, Bf",
    "Spagl-Straße",
    "Heribert-Stephan-Straße",
    "Hausmanning",
    "Östererweg",
    "Pocking, Bahnhof (1)",
    "Pocking Bahnhof",
    "Schwammerlweg Nr.14",
    "Hundsdorf",
    "Otto-Punk-Straße",
    "Abt-Zanker-Straße",
    "Kronberger Straße",
    "Sparkassenstraße",
    "Matheisstraße",
    "Franz-Josef-Streibl-Straße",
    "Schwester-Renata-Hampel-Straße",
    "Salzgattern",
    "Bürgermeister-Krah-Allee",
    "Bäckerreuthweg",
    "Thomas-Stöber-Straße",
    "Bgm.-Dobler-Straße",
    "In der Schaar",
    "Nr. 2",
    "Büchlweg",
    "Paumgartnerstraße",
    "Ludlfeld",
    "Kohlstattweg",
    "Pfarrer-Vietzke-Straße",
    "Dr.-Julius-Mayr-Straße",
    "Bürgermeister-Hartl-Straße",
    "Rosi-Obermüller-Straße",
    "Anton-Brandl-Platz",
    "Urfarer Straße",
    "Pfarrer-Schanderl-Weg",
    "Am Gasteig",
    "Zanderweg",
    "Seeweg",
    "Sebastian-Schütz-Straße",
    "Asbacher Straße",
    "Am Waldblick",
    "Kiesweg",
    "Am Jackinger Berg",
    "Bischof-Eder-Straße",
    "Mühlfeld",
    "Hammerleiten",
    "Pointenweg",
    "Aichaer Straße",
    "Obere Birkastraße",
    "Hans-Hösl-Straße",
    "Thann",
    "Doblsteiner Weg",
    "Carl-Orff-Straße",
    "Beethovenring",
    "Richard-Strauss-Ring",
    "Brunecker Straße",
    "Auckentalweg",
    "Pfarrer-Zellbeck-Weg",
    "Im Mitterfeld",
    "Bauzinger Straße",
    "Duschlberg",
    "Fuchsleite",
    "Fürstenzell, Heimvolksschule",
    "Wassertörlschanze",
    "Schumannstraße",
    "Schellköpfing",
    "Bräuhausstraße",
    "Georg-Doppelhammer-Weg",
    "Sonnenfeld",
    "Alte Siedlung",
    "Burgerholzweg",
    "Trifterner Straße",
    "Guggstraße",
    "Weinbergerweg",
    "Wöhrlweg",
    "Hirschsteinblick",
    "Am Fernsehturm",
    "Leitenwiesweg",
    "Kalterschlagweg",
    "Ilztalweg",
    "Ilztalring",
    "Mondseeweg",
    "Wolfachtalweg",
    "Am Haidenburger Berg",
    "Rastplatz Hammerbach",
    "Robert-Daiser-Straße",
    "Heuwinkel",
    "Hans-Preu-Weg",
    "Zum Bräukeller",
    "Pauerstraße",
    "Schinderweg",
    "Schambacher Straße",
    "Franz-Schwarz-Straße",
    "Weisching",
    "Am Schacherfeld",
    "Bärnbach",
    "Straßfeld",
    "Hinterschloßweg",
    "Hafering",
    "Werner-Heyd Weg",
    "Rannafeld",
    "Denkmalweg",
    "Martinsweg",
    "Brauchsdorfer Straße",
    "St.-Michael-Straße",
    "Sattlerbrücke",
    "Matzenberger Straße",
    "Gruber Feld",
    "Alfons-Gerstl-Straße",
    "Georg-Well-Straße",
    "Eisenbirner Straße",
    "Zur Schutzbrücke",
    "Freihofer Ring",
    "Anton-Nöbl-Straße",
    "Lindahofring",
    "Karl-Föckerer-Straße",
    "Herrnwald",
    "Am Radweg",
    "Eginger Feld",
    "Pfarrer-Klinger-Straße",
    "Donauleite",
    "Harry Niewert Weg",
    "Waldblickweg",
    "Fürstensteig",
    "Vorwaldstraße",
    "Am Fuchsberg",
    "St 2323",
    "St 2318",
    "Rohrbachholz",
    "Asenfeld",
    "Mirabellenweg",
    "Hengstenberg",
    "Oberfrauenwalder Weg",
    "Alter Kirchenweg",
    "Schustergarten",
    "Am Bärnbach",
    "Bartlmühle",
    "Jungbauerngasse",
    "Zur Painten",
    "Waldlmühle",
    "Meßnerschlagerwaide",
    "Werthmannweg",
    "Marie-Juchacz-Straße",
    "IT-Zentrum",
    "An der Goldscheibe",
    "Pfarrer - Bergmann - Steig",
    "Am Berg",
    "Wiesenfeld",
    "Mooshamer Feld",
    "Pfarrer-Siegfried-Kroiß Straße",
    "Wanderweg",
    "Untere Hofmark",
    "Kleiner Trail",
    "Scharäcker",
    "Erläcker",
    "Waldblick",
    "Bäckerreihe",
    "Bernau",
    "Passau, ZOB",
    "Rastplatz Geißberg",
];